FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build

ARG BUILD_CONFIGURATION=Release

WORKDIR /src
COPY . .

RUN dotnet publish "LearnWord.Migrator/LearnWord.Migrator.csproj" \
      -c "${BUILD_CONFIGURATION}" \
      -o /out \
      /p:UseAppHost=false

FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS final

WORKDIR /migrations
COPY --from=build /out .

ENTRYPOINT ["dotnet", "LearnWord.Migrator.dll"]
