name: learnword-build

services:
  migrations:
    image: ${LW_IMAGE_PREFIX:-learnword}/migrations:${LW_IMAGE_TAG:-local}
    platform: ${LW_PLATFORM:-linux/amd64}
    build:
      context: ../LearnWord
      dockerfile: Dockerfile.migrations

  learnword.webapi:
    image: ${LW_IMAGE_PREFIX:-learnword}/learnword-webapi:${LW_IMAGE_TAG:-local}
    platform: ${LW_PLATFORM:-linux/amd64}
    build:
      context: ../LearnWord
      dockerfile: LearnWord.WebApi/Dockerfile

  learnword.identity:
    image: ${LW_IMAGE_PREFIX:-learnword}/learnword-identity:${LW_IMAGE_TAG:-local}
    platform: ${LW_PLATFORM:-linux/amd64}
    build:
      context: ../LearnWord
      dockerfile: LearnWord.Identity/Dockerfile

  identityservice:
    image: ${LW_IMAGE_PREFIX:-learnword}/identityservice:${LW_IMAGE_TAG:-local}
    platform: ${LW_PLATFORM:-linux/amd64}
    build:
      context: ../LearnWord
      dockerfile: IdentityService.WebApi/Dockerfile

  gateway:
    image: ${LW_IMAGE_PREFIX:-learnword}/gateway:${LW_IMAGE_TAG:-local}
    platform: ${LW_PLATFORM:-linux/amd64}
    build:
      context: ../LearnWord
      dockerfile: LearnWord.Gateway/Dockerfile

  webapp:
    image: ${LW_IMAGE_PREFIX:-learnword}/webapp:${LW_IMAGE_TAG:-local}
    platform: ${LW_PLATFORM:-linux/amd64}
    build:
      context: ../../LearnWordWebApp/lw-app
      dockerfile: Dockerfile
